variables <- list()
variables$MGDP$summary <- c("ECYC", "ECY6", "ECY9", "ECY2")
variables$MGDP$services <- c("ECYD", "ECYG", "ECYH", "ECYI", "ECYJ", "ECYK",
                             "ECYL", "ECYP", "ECYQ", "ECYR", "ECYS", "ECYT",
                             "ECYU", "ECYV")
variables$DRSI$summary <- c("J5C4", "J5EK")
variables$DRSI$detail <- c("EAQW", "EAQX", "EARA", "EARB", "EAQZ", "J5BI")
variables$MRET$summary <- c("LGCN", "LGDF", "LGEB", "LGEU")
variables$MRET$summary_no_erratics <- c("SDCY", "SDDR", "SDEK", "SDFC")
variables$LMS$summary <- c("LF2Q") #, "LF9D", "LF22", "LF2S")
variables$LMS$inactivity <- c("LWFA", "LWFD", "LWFG", "LF2W")
variables$LMS$inactivity_sick <- c("LF69") #, "LF67")
variables$LMS$employment <- c("LF2G") # "MGSR")
variables$LMS$unemp_rates <- c("MGXB", "YBVW", "YBVQ", "LF2Q")
variables$LMS$earnings <- c("KAC2", "KAC5", "KAC8", "K5CB")
variables$LMS$vacancies <- c(paste0("JPA", 2:9), paste0("JPB", 2:9), paste0("JPC", 2:3))
variables$UKEA$savings_ratio <- c("DGD8")
variables$MM23$summary <- c("D7G7", "L55O", "CZBH")
variables$MM23$goods_services_core <- c("D7NM", "D7NN", "DKO8")
variables$MM22$producer_prices <- c("GHIP", "GB7S")
