name: Push data files

'on':
  push:
    branches:
      - main
    paths:
      - data/parquet
  workflow_dispatch:

jobs:
  push-data-files:
    name: Push parquet files to EA server
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      changes: ${{ steps.updated.outputs.changes }}
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4

      - name: SSH Sync Action
        uses: Lexty/ssh-sync-action@v1.0.0
        with:
          host: ${{ secrets.EA_SFTP_SERVER }}
          user: ${{ secrets.EA_SFTP_USERNAME }}
          key: ${{ secrets.EA_SFTP_SSH }}
          rsync_upload: |
            ./data/parquet/ => /opt/sites/data.economic-analytics.co.uk/edd/
            ./data/edd_dict.csv => /opt/sites/data.economic-analytics.co.uk/edd/
